/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_james_ndk_practice_NDKPracticeActivity */

#ifndef _Included_com_james_ndk_practice_NDKPracticeActivity
#define _Included_com_james_ndk_practice_NDKPracticeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_james_ndk_practice_NDKPracticeActivity
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_james_ndk_1practice_NDKPracticeActivity_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
